# Generated by Django 3.1.6 on 2021-08-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('addr', models.CharField(max_length=40)),
                ('phno', models.IntegerField()),
                ('uname', models.CharField(max_length=20)),
            ],
        ),
    ]
