# Generated by Django 3.1.6 on 2021-08-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('paswd', models.CharField(max_length=15)),
                ('type', models.IntegerField(verbose_name=2)),
            ],
        ),
    ]
